package unienroll.domain;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.ArrayList;
import java.util.List;

// TODO: add validation with exceptions
public class Course {
    static long counter = 100L;

    //    TODO: courseId should be generated by the database & subject name initials
    //    TODO: courseId need to be unique and threadsafe
    private final String courseId;
    private String title;
    private String description;
    //    TODO: Make instructorId a reference to the instructor
    private String instructorId;
    private final List<String> enrolledStudentsId;
    private int capacity;

    // default constructor
    public Course(String title, String description, String instructorId, int capacity) {
        setTitle(title);
        setDescription(description);
        setInstructorId(instructorId);
        setCapacity(capacity);
        this.enrolledStudentsId = new ArrayList<>();
        courseId = "NSU-" + counter++;
    }

    @JsonCreator
    public Course(
            @JsonProperty("courseId") String courseId,
            @JsonProperty("title") String title,
            @JsonProperty("description") String description,
            @JsonProperty("instructorId") String instructorId,
            @JsonProperty("capacity") int capacity,
            @JsonProperty("enrolledStudentsId") List<String> enrolledStudentsId
    ) {
        setTitle(title);
        setDescription(description);
        setInstructorId(instructorId);
        setCapacity(capacity);
        this.enrolledStudentsId = enrolledStudentsId;
        this.courseId = courseId != null ? courseId : "NSU-" + counter++;
    }

    public String getCourseId() {
        return courseId;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitle() {
        return title;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setInstructorId(String instructorId) {
        this.instructorId = instructorId;
    }

    public String getInstructorId() {
        return instructorId;
    }

    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }

    public int getCapacity() {
        return capacity;
    }

    public int getEnrolledStudentsCount() {
        return enrolledStudentsId.size();
    }

    public void enrollStudent(String studentId) {
        //    TODO: Don't know how to catch this error yet but putting it here for good measure
        if (!hasAvailableSeat()) {
            throw new IllegalStateException("Course is full");
        }
        enrolledStudentsId.add(studentId);
    }

    public void removeStudent(String studentId) {
        enrolledStudentsId.remove(studentId);
    }

    public boolean hasAvailableSeat() {
        return capacity > enrolledStudentsId.size();
    }

    @Override
    public String toString() {
        return "Course{" +
                "courseId='" + courseId + '\'' +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", instructorId='" + instructorId + '\'' +
                ", capacity=" + capacity +
                ", enrolledStudentsCount=" + enrolledStudentsId.size() +
                ", enrolledStudentsId=" + enrolledStudentsId +
                '}';
    }
}
